### ISSUE TITLE
OP: QueryFinalityProviderHasPower

### ISSUE THREAD

**Issue by bap2pecs** [babylonchain/finality-provider#496]
## Context

per my discussion w @SebastianElvis, we can just hardcode to a positive value b/c so this interface function is only used for checking if the FP is eligible for submitting sigs

but it's still useful. at least honest FPs won't submit useless data

so post-mvp we can do this per @SebastianElvis 's suggestion

> A possible algorithm is as follows: instead of querying the exact voting power, the FP queries BTC delegations page by page, and if there is >=1 active BTC delegation, then it can vote.

> Another way is that FP leverages backend service that indexes voting power for Babylon. This introduces some unnecesasry coupling though

I am in favor of approach one

## Tasks

- [x] check all the call sites to see if we can rename to `QueryFinalityProviderHasPower`
- [x] refactor to `QueryFinalityProviderHasPower`: #507 
- [x] instead of querying the exact voting power, the FP queries BTC delegations page by page, and if there is >=1 active BTC delegation, then it can vote.

**Comment by bap2pecs** [comment]
> @bap2pecs can you please help me understand the issue so as per my understanding:
> 
> 
> 
> i understand this interface fn is only used while submitting sigs, so is the intention of pr to use a efficient/better query to achieve this? 
> 
> 
> 
> Currently as you said we are querying power at a given height but the proposed algorithm (finding delegations page by page sounds inefficient?)

yes the idea is we don't need to find the exact voting power. as long as we find one active delegation, we can return true

**Comment by bap2pecs** [comment]
> i see, so you'll need to query fp delegation with the active status but looking at the query code i think
> 
> [FinalityProviderPowerAtHeight](https://github.com/babylonchain/babylon-private/blob/d64ddc97d1c8b9f695b814b7b1b92ce133f2547b/x/btcstaking/keeper/grpc_query.go#L125) is still more efficient operation than doing [FinalityProviderDelegations](https://github.com/babylonchain/babylon-private/blob/d64ddc97d1c8b9f695b814b7b1b92ce133f2547b/x/btcstaking/keeper/grpc_query.go#L223) cc @SebastianElvis 

to clarify a bit, there are two goals:

1) tighten the interface - this PR
2) improve the efficiency/implementation - next PR

**Comment by bap2pecs** [comment]
all tasks done
